version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=ourverysecuresecretkey
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DJANGO_SETTINGS_MODULE=task.settings.production
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=verysecurepassword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task
    expose:
      - "5432"
  redis:
    image: redis:6.2.7-alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A task worker -l info
    volumes:
      - ./.:/task
    environment:
      - SECRET_KEY=ourverysecuresecretkey
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=task.settings.production
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build:
      context: .
    command: celery -A task beat -l info
    volumes:
      - ./.:/task
    environment:
      - SECRET_KEY=ourverysecuresecretkey
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=task.settings.production
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data: