# Generated by Django 4.1.7 on 2023-03-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="blocked_credit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=15)),
                ("price", models.DecimalField(decimal_places=4, max_digits=25)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "created"),
                            ("IN_PROGRESS", "in_progress"),
                            ("FINALIZED", "finalized"),
                            ("FAILED", "failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crypto.cryptocurrency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crypto.account"
                    ),
                ),
            ],
        ),
    ]
