# Generated by Django 4.1.7 on 2023-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0003_alter_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "created"),
                    ("IN_PROGRESS", "in_progress"),
                    ("REQUEST_SENT", "request_sent"),
                    ("FINALIZED", "finalized"),
                    ("FAILED", "failed"),
                ],
                max_length=20,
            ),
        ),
    ]
